{%set name = "flask-cache" %}
{%set camelName = "Flask-Cache" %}
{%set version = "0.13.1" %}
{%set hash_type = "sha256" %}
{%set hash_val = "90126ca9bc063854ef8ee276e95d38b2b4ec8e45fd77d5751d37971ee27c7ef4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ camelName }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - flask

  run:
    - python
    - flask

test:
  imports:
    - flask_cache

about:
  home: http://github.com/thadeusb/flask-cache
  license: BSD 3-Clause
  summary: 'Adds cache support to your Flask application'

extra:
  recipe-maintainers:
    - pmlandwehr
